version: 2
formats: [
  "pdf"
]

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

build:
  os: ubuntu-22.04
  apt_packages:
    - inkscape
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - pip install .[all] .[docs]
      - python3 ./docs/setup.py --start-dir source
