# CONSTANTS
C_BOT_API_KEY = "OTA5MzgyNDE3MDg3ODgxMjc2.YZDeXw.2oH3R1ESb_8oVGdUFnfm_wZc4Oo"
C_DEBUG = True
C_FILE_OUTPUT = True
C_IS_USER = False

## Hour constants
C_DAY_TO_SECOND = 86400
C_HOUR_TO_SECOND= 3600
C_MINUTE_TO_SECOND = 60